project:
  type: website
  output-dir: docs
exclude:
    - "*.Rmd"
    - "**/*.Rmd"
    
website:
  title: "BEACONs R Tools"
  image: "pics/bp_banner.png"
  navbar:
    background: primary
    right:
      - text: "More"
        menu:
          - text: "BEACONs Website"
            href: https://beaconsproject.ualberta.ca/
          - text: "Report an Issue"
            href: https://github.com/beaconsproject/R_tools_public/issues
    left:
      - href: index.qmd
        text: Welcome
      - text: "Functions categories"
        menu:
          - href: tools/Builder_index.qmd
            text: Builder    
          - href: tools/Spatial_index.qmd
            text: Spatial
      - text: "Articles"
        menu:
          - href: vignettes/createBuilderInput.qmd
            text: Create Builder Input    
          - href: vignettes/createBuilderPolygons.qmd
            text: Create Builder Polygons
          - href: vignettes/calcDCI.qmd
            text: Calculate DCI
format:
  html:
    include-after-body: _includes/footer.html
    theme: 
      light: [cosmo, theme.scss]
    css: styles.css
    toc: true

resources:
  - downloads/*