project:
  type: website
  output-dir: docs
  exclude:
    - "*.Rmd"
    - "**/*.Rmd"
    
website:
  title: "BEACONs R Tools"
  image: "pics/bp_banner.png"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - text: "Data"
        menu:
          - href: data/yt_data.qmd
            text: Yukon    
          - href: data/bc_data.qmd
            text: BC
      - href: resources.qmd

format:
  html:
    theme: 
      light: [cosmo, theme.scss]
    css: styles.css
    toc: true