## BEACONs Representation R Functions
BEACONs developped a variety of functions for two types of representation analysis: 

The `calc_dissimilarity()` function compares the distributions of a raster layer between a conservation area and a broader study region that we are trying to represent. The closer the distributions of raster values, the lower the dissimilarity score. Values of 0.2 or less are considered 'good' representation. 

Another approach focus on reaching target-based target using proportional representation. The latter ensure specific target areas of different representation classes are met in one or multiple conservation areas.  

Representation analyses typically include multiple layers assumed to represent a range of ecological processes. They often include climate layers, productivity, riparian zones etc. The goal of the representation analysis is to identify conservation areas that adequately capture the target amounts of representation classes (in our case NALC classes) deemed to be proportionally representative of the study region. Usually the target amounts should be met in full in a conservation area, rather than being split between multiple conservation areas. The idea being that the conservation area should provide a sufficient area for the ecological processes associated with specific target classes to operate. In a network of multiple conservation areas, different target classes and different ecological processes may therefore be represented by different conservation areas.


**The xx main representation functions are:**

- [calc_dissimilarity](calc_dissimilarity.qmd)
- [evaluate_criteria_using_clip](evaluate_criteria_using_clip.qmd)
- [criteria_to_catchments](criteria_to_catchments.qmd)
- [gen_targets](gen_targets.qmd)
- [evaluate_targets_using_catchments](evaluate_targets_using_catchments.qmd)
- [evaluate_targets_using_clip](evaluate_targets_using_clip.qmd)

### calc_dissimilarity

The function [calc_dissimilarity()](calc_dissimilarity.html) calculate dissimilarity values between a set of polygons and a reference area..


### evaluate_criteria_using_clip

The function [evaluate_criteria_using_clip()](evaluate_criteria_using_clip.html) clips the criteria raster to the conservation area and calculates the proportion of each class within it.

### criteria_to_catchments

The function [criteria_to_catchments()](criteria_to_catchments.html) sums the area of all unique values in the raster and adds summed area's as columns in the catchments dataset.


### gen_targets

The function [gen_targets()](gen_targets.html) clips the criteria raster to the conservation area and calculates the proportion of each class within it.


### evaluate_targets_using_catchments

The function [evaluate_targets_using_catchments()](evaluate_targets_using_catchments.html) evaluate targets using conservation areas created by **Builder** which are defined by lists of catchments. 

### evaluate_targets_using_clip

The function [evaluate_targets_using_clip()](evaluate_targets_using_clip.html) clips the criteria raster to the conservation area and calculates the proportion of each class within it.

<br>
<br>

## Citation
Houle M, Vernier P, Lisgo K, Edwards M, Schmiegelow F (2025). BEACONs R_Tools_Public: Building conservation areas in R. Available at https://beaconsproject.github.io/R_tools_public/.