## BUILDER R Functions

# `reserve_seeds()`

The `reserve_seeds()` function creates a **seeds table** based on conservation areas, which is an input to `builder()`.  
It identifies **seed catchments inside a conservation area** and assigns them an **area target**.

Seed catchments are the starting points for constructing benchmarks.  
This function provides methods for filtering the catchments dataset and assigning area targets.

## Usage

```r
reserve_seeds(
  catchments_sf,
  CAs_sf,
  CAs_name = NULL,
  areatarget_value = NULL,
  joinType = NULL
)
```
## Arguments

- catchments_sf: sf object of the catchments dataset with a unique identifier column: CATCHNUM.

- CAs_sf: A character string. Name of the column holding conservation area unique identifiers.

- CAs_name: A character string. Name of the column holding conservation area unique identifiers.

- areatarget_value: (Optional) A single numeric value specifying the area target to apply to all seeds.

- joinType: A character string. Type of spatial join to identify catchments within conservation areas. 
Options are `"INTERSECT"` or `"CENTROID"`. Default is `"CENTROID"`.

## 📤 Output
A tibble of reserve seed catchments and their associated area targets.


## Examples
### Running the examples

1. Create the folder structure
```r
# Set working directory
setwd("your/path/to/downloads")

dirpath <- getwd()

# Create the folder structure
treedir <- c("R","data","Builder_input")
for(d in treedir){
  if (!dir.exists(file.path(dirpath, d))) {
    dir.create(file.path(dirpath, d), recursive = TRUE)
  }
}
```

2. Download the functions, data and example files and save them in the proper folder.
- <a href="../downloads/builder.R" download>Download builder functions in the R folder</a>
- <a href="../downloads/catchments_sample.rds" download>Download catchments sample in the data folder</a>
- <a href="../downloads/reserves_sample.rds" download>Download reserves sample in the data folder</a>
- <a href="../downloads/example-reserve_seeds-script.R" download>Download reserve_seeds example R script</a>

2. In R, either:
   - Place the files in your working directory (`getwd()`), or
   - Update the path in the examples using a `data_path` variable.
3. Run the examples below.

```r
library(dplyr)
library(sf)
library(utils)

source("./R/builder.R")

# Use all catchments as seeds with a single area target
catchments_sample <- readRDS("data/catchments_sample.rds")
reserves_sample <- readRDS("data/reserves_sample.rds")
reserve_seeds(catchments_sf = catchments_sample, CAs_sf = reserves_sample, CAs_name = "reserve", areatarget_value = 1000000000)

# save seeds as csv
reserve_seed <- reserve_seeds(catchments_sf = catchments_sample, CAs_sf = reserves_sample, CAs_name = "reserve", areatarget_value = 1000000000)
write.csv(reserve_seed, file=file.path(dirpath,"Builder_input/reserve_seeds.csv"), na = "", row.names=FALSE)
```

